CREATE USER goals WITH PASSWORD 'goals';
CREATE DATABASE goals;
GRANT ALL PRIVILEGES ON DATABASE goals TO goals;
ALTER DATABASE goals OWNER TO goals;

CREATE USER sonar WITH PASSWORD 'sonar';
CREATE DATABASE sonar;
GRANT ALL PRIVILEGES ON DATABASE sonar TO sonar;
ALTER DATABASE sonar OWNER TO sonar;
