services:

  tomcat:
    container_name: tomcat
    image: tomcat:10.1.13-jdk17-temurin-jammy
    ports:
      - 8081:8080
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk17
    user: root
    ports:
      - 8082:8080
    volumes:
      - jenkins_user_home:/root
      - jenkins_home:/var/jenkins_home
      - tomcat_webapps:/usr/local/tomcat/webapps

  postgres:
    container_name: postgres
    image: local/postgres:15.4-alpine-sonar
    build:
      context: ./postgres
      dockerfile: ./postgres.dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9.2-community
    depends_on:
      - postgres
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar

volumes:
  tomcat_webapps:
  jenkins_home:
  jenkins_user_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
